name: Build

on:
  pull_request:
    branches:
      - insights

jobs: 
  build:
    name: Build
    if: '! github.event.pull_request.draft'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with: 
          submodules: true
      - name: Build collectd in docker
        run: |
          set -x
          RELEASE_VERSION="7.7.7"
          debugoutput="insights-collectd-debug-${RELEASE_VERSION}.tar.gz"
          outputgz="insights-collectd-${RELEASE_VERSION}.tar.gz"
          outputzip="insights-collectd-${RELEASE_VERSION}.zip"

          image=collectd-bundle
          docker build --build-arg insight_version=${RELEASE_VERSION} -t $image .
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
